/** Small local cosmetic hide list — not a full uBO engine. */
export const COSMETIC_SELECTORS = [
  // Google / AdSense
  '[id*="google_ads"]',
  '[id*="GoogleAd"]',
  '[class*="google-ad"]',
  '[class*="GoogleAd"]',
  'ins.adsbygoogle',
  '[data-ad-slot]',
  '[data-ad-client]',
  '[data-ad]',
  '[data-ads]',
  '[data-adunit]',
  '[data-google-query-id]',
  // Generic ad containers
  '.ad-banner',
  '.ad-container',
  '.ad-slot',
  '.ad-wrapper',
  '.ad-unit',
  '.adbox',
  '.adsbox',
  '.adsbygoogle',
  '.advert',
  '.advertisement',
  '.advertising',
  '.adhesion-ad',
  '.sponsored',
  '.sponsored-content',
  '.sponsored-post',
  '.sponsor-unit',
  '.dfp-ad',
  '.dfp_ad',
  '.mpu-ad',
  '.promo-ad',
  '.native-ad',
  '.taboola',
  '.trc_rbox',
  '[id*="taboola"]',
  '[class*="taboola"]',
  '[id*="outbrain"]',
  '[class*="outbrain"]',
  '[class*="Outbrain"]',
  // Structural guesses (kept conservative)
  'aside[class*="ad-"]',
  'aside[id*="ad-"]',
  'div[class^="ad-"]',
  'div[class*=" ad-"]',
  'div[class$="-ad"]',
  'div[class*="-ad-"]',
  'div[id^="ad-"]',
  'div[id*="AdContainer"]',
  'div[id*="adcontainer"]',
  'div[id*="ad-container"]',
  'div[id^="div-gpt-ad"]',
  'div[id^="gpt_ad"]',
  'section[class*="ad-"]',
  // Iframes
  'iframe[src*="doubleclick.net"]',
  'iframe[src*="googlesyndication.com"]',
  'iframe[src*="googletagservices.com"]',
  'iframe[src*="amazon-adsystem.com"]',
  'iframe[id^="google_ads_iframe"]',
  'iframe[title="Advertisement"]',
  'iframe[title="Ads"]',
  // ARIA / labels
  '[aria-label="Ads"]',
  '[aria-label="Advertisement"]',
  '[aria-label="Advertisements"]',
  '[aria-label*="Advertisement"]',
];
